name: scrobblenaut
description: A deadly simple LastFM API Wrapper for Dart. So deadly simple that it's gonna hit the mark.
version: 2.0.5
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  json_annotation: ^3.0.1
  convert: ^2.1.1
  dio: ^3.0.9
  crypto: ^2.1.5
  xml: ^4.2.0
  universal_io: ^1.0.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.6
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
